version: "3.9"
services:
  dbDemo:
    container_name: dbDemo
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/home/nostra/postgre-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: nostra
      POSTGRES_USERNAME: nostra
      POSTGRES_DATABASE: nostra
  apps:
    container_name: appsDemo
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - dbDemo
