version: "3.9"
services:
  apps:
    image: app-images
    build: .
    ports:
      - "8080-8090:8080"
    links:
      - dbDemo
  dbDemo:
    container_name: dbDemo
    image: postgres
    volumes:
      - "/home/nostra/postgre-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: nostra
      POSTGRES_USERNAME: nostra
      POSTGRES_DATABASE: nostra
  nginx:
    container_name: nginxDemo
    image: nginx
    restart: always 
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8091:8091"
    links:
      - apps