version: "3.9"
services:
  apps:
    container_name: appsDemo
    build: .
    ports:
      - "8080:8080"
    links:
      - dbDemo
  dbDemo:
    container_name: dbDemo
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/home/nostra/postgre-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: nostra
      POSTGRES_USERNAME: nostra
      POSTGRES_DATABASE: nostra
  nginx:
    container_name: nginxDemo
    image: nginx
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - apps
