version: "3.9"
services:
  apps:
    image: app-images
    build: .
    volumes:
      - "app_volume:/logs"
  apps2:
    image: app-images
    build: .
    volumes:
      - "app_volume:/logs"
  dbDemo:
    container_name: dbDemo
    image: postgres
    volumes:
      - "db_volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: nostra
      POSTGRES_USERNAME: nostra
      POSTGRES_DATABASE: nostra
  nginx:
    container_name: nginxDemo
    image: nginx
    restart: always 
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7001:8080"
    links:
      - apps

volumes:
  app_volume:
    driver_opts:
      type: none
      o : bind
      device: ./data
  db_volume:
    driver_opts:
      type: none
      o: bind
      device: ./postgre-data
